### ISSUE TITLE
Polylang doesn't work with autoloader on fresh install

### ISSUE THREAD

**Issue by sandrodz** [wordplate/autoloader#2]
Moving it to plugins, activating, and moving it back to mu-plugins dir fixes the issue.

Any ideas why?

**Comment by tditlu** [comment]
Polylang have a hook that waits for 'plugins_loaded', will check if this hook is called before mu-plugins is activated.
I'm on it!

**Comment by tditlu** [comment]
@sandrodz Try the latest commit:
https://github.com/wordplate/autoloader/commit/3de6260f05ae1c208ff4180b243f06ea571b7e8d

**Comment by vinkla** [comment]
I've released a new version with the fix. Please run an update to get the latest changes.

**Comment by sandrodz** [comment]
Awesome, ty.
